---
abstract: 'Relaxing interface to SQLite'
author:
  - 'Lubomir Rintel <lkundrak@v3.sk>'
build_requires:
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
  Test::Pod: 1.00
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Database-DumpTruck
provides:
  Database::DumpTruck:
    file: lib/Database/DumpTruck.pm
    version: 1.1
requires:
  B: 0
  DBD::SQLite: 0
  DBI: 0
  JSON: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Database-DumpTruck
  license: http://dev.perl.org/licenses/
  repository: https://github.com/lkundrak/perl-database-dumptruck
version: 1.1
